export const HTTP_RESPONSE = {
	OK: 200,
	Created: 201,
	BadRequest: 400,
	Unauthorized: 401,
	Forbidden: 403,
	NotFound: 404,
	MethodNotAllowed: 405,
	InternalServerError: 500,
	NotImplemented: 501,
} as const;

export const SCHEMA_ERRORS_CODE = {
	// 'const': 'const Schema Error', 
	// 'dependentRequired': 'dependentRequired Schema Error',
	'enum': 'must be equal to one of the allowed values',
	'format': 'must match format',
	// 'maximum': 'maximum Schema Error',
	'minimum': 'must be >=',
	// 'exclusiveMaximum': 'exclusiveMaximum Schema Error',
	// 'exclusiveMinimum': 'exclusiveMinimum Schema Error',
	// 'maxProperties': 'maxProperties Schema Error',
	'pattern': 'must match pattern',
	'uniqueItems': 'must NOT have duplicate items',
	'additionalProperties': 'must NOT have additional properties',
	'minLength': 'must NOT have fewer than',
	'maxLength': 'must NOT have more than',
	'minProperties': 'must NOT have fewer than 1 properties',
	'required': 'must have required property',
	'number': 'must be number',
	'string': 'must be string',
	'array': 'must be array',
	'object': 'must be object',
	'boolean': 'must be boolean',
} as const;
